### ISSUE TITLE
Error when deploying to Umbraco Cloud

### ISSUE THREAD

**Issue by tonypye** [harikrishna43/UmbracoForms.Mailchimp.WorkFlow#10]
After adding the package via NuGet and running locally, then deploying to Umbraco Cloud development environment the front-end and backoffice shows a 'Culture is not supported' error (YSOD)

1. Install package locally via Nuget
2. Open the locally running website (backoffice) and configure the workflow settings to check it's adding subscribers into Mailchimp
3. Commit and push changes to UmbracoCloud development environment
4. Try to open the development URL - the following YSOD error is presented:

Culture is not supported.
Parameter name: name
in is an invalid culture identifier.

I can't see anything in your UFMailChimpWorkFlowType.cs file to cause this, so any idea on what might be causing this error?

Any help on this would be great.

![FireShot Capture 055 - Culture is not supported {br}Parameter name_ name{br}in is an invalid_ - dev-the-clothworkers-company s1 umbraco io](https://user-images.githubusercontent.com/20457914/92381439-c674e680-f102-11ea-87a4-ddaf28cbc3cb.png)

**Comment by harikrishna43** [comment]
Sorry for the issue in this package. Issued fixed need to update package.
I'll update the package and you can use that.
*Regards,*

[image: Logo] <https://www.madnattechnologies.com/> [image: Logo]
Harikrishna Parmar
Software Engineer
M: +91 9726343170
E: parmar.harikrishna43@gmai.com | www.madnattechnologies.com
Ahmedabad
[image: Facebook icon] <https://www.facebook.com/krish.parmar43> [image:
LinkedIn icon] <https://www.linkedin.com/in/harikrishna-parmar/> [image:
Twitter icon] <https://twitter.com/hk_netdeveloper> [image: Instagram icon]
<https://www.instagram.com/madnattechnologies/>
[image: Banner] <https://www.madnattechnologies.com/>

**Comment by harikrishna43** [comment]
hi @tonypye 
the package is updated. Please try the latest package and let me know if not works.

**Comment by tonypye** [comment]
Hi Harikrishna

Thank you for looking into this so quickly. I'll download the package today and let you know if this has sorted the problem

Kind regards

Tony

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tonypye** [comment]
Hi Harikrishna

Sorry, I’ve tried updating the package, and also removing it completely and re-adding it and it’s still showing the same error.

Any ideas?

Kind regards

Tony

**Comment by harikrishna43** [comment]
I tried to fix the issue to update the culture.  Updated package. please let me know if any issue.
Thanks
HK

**Comment by tonypye** [comment]
Hi Harikrishna

I can confirm its now working as expected on Umbraco Cloud

Many thanks for looking into this

Kind regards

Tony

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
