### ISSUE TITLE
Looks like this package will kill umbraco 8.6 if it's installed from backoffice

### ISSUE THREAD

**Issue by saadan** [harikrishna43/UmbracoForms.Mailchimp.WorkFlow#6]
**Describe the bug**
My site crashed and can't restart

**To Reproduce**
1. Just download and install the package on a umbraco 8.6
2. and run the site I get Umbraco.Core.Exceptions.BootFailedException: Boot failed.

Think it misses dependencies

**Update**
Work if you install it with nuget.

**Comment by harikrishna43** [comment]
Sorry for the issue. I will fix this issue soon.
