### ISSUE TITLE
Installation via a package

### ISSUE THREAD

**Issue by thenexus00** [harikrishna43/UmbracoForms.Mailchimp.WorkFlow#9]
Hi there,
I discovered an issue with the package installing via the admin or downloading local. On installation the Mmbraco 8 site dies with a system error regarding missing references.
The package requires a nuget Mailchimp package that is not included in Umbraco projects to be added to the project in Visual Studio.
Doing so and everything is good.
This should be part of the instructions.

**Comment by harikrishna43** [comment]
Thanks, @thenexus00 I will fix this issue and will update the package soon. 
Thanks for feedback.

**Comment by harikrishna43** [comment]
@thenexus00  FIxed issue. Updated package in v3.0.1.
